--------------------------------------------------------
--  Fichier créé - dimanche-février-22-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_POUBELLE
--------------------------------------------------------

   CREATE SEQUENCE  "TUNIWASTE"."SEQ_POUBELLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Table POUBELLE
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."POUBELLE" 
   (	"ID_POUBELLE" NUMBER, 
	"LOCALISATION" VARCHAR2(255), 
	"NIVEAU" NUMBER(5,2), 
	"ETAT" VARCHAR2(30), 
	"TYPE" VARCHAR2(50), 
	"ID_ZONE" NUMBER NOT NULL ENABLE, 
	"ID_CENTRE" NUMBER, 
	"ID_UTILISATEUR" NUMBER, 
	"ID_CAMION" NUMBER, 
	 PRIMARY KEY ("ID_POUBELLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_POUBELLE_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "TUNIWASTE"."ZONE" ("ID_ZONE") ENABLE, 
	 CONSTRAINT "FK_POUBELLE_CENTRE" FOREIGN KEY ("ID_CENTRE")
	  REFERENCES "TUNIWASTE"."RECYCLAGE" ("ID_CENTRE") ENABLE, 
	 CONSTRAINT "FK_POUBELLE_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE, 
	 CONSTRAINT "FK_POUBELLE_CAMION" FOREIGN KEY ("ID_CAMION")
	  REFERENCES "TUNIWASTE"."CAMION" ("ID_CAMION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table CAMION
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."CAMION" 
   (	"ID_CAMION" NUMBER, 
	"TYPE_CAMION" VARCHAR2(50), 
	"CAPACITE" NUMBER(10,2), 
	"STATUT" VARCHAR2(30), 
	"CHAUFFEUR" VARCHAR2(100), 
	"NUM_CHAUFFEUR" VARCHAR2(20), 
	"ID_UTILISATEUR" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CAMION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_CAMION_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table RECYCLAGE
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."RECYCLAGE" 
   (	"ID_CENTRE" NUMBER, 
	"RESPONSABLE" VARCHAR2(100), 
	"TYPE_DECHET" VARCHAR2(50), 
	"QUANTITE" NUMBER(10,2), 
	"DATE_RECYCLAGE" DATE, 
	"ID_POUBELLE" NUMBER, 
	 PRIMARY KEY ("ID_CENTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_RECYCLAGE_POUBELLE" FOREIGN KEY ("ID_POUBELLE")
	  REFERENCES "TUNIWASTE"."POUBELLE" ("ID_POUBELLE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ZONE
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."ZONE" 
   (	"ID_ZONE" NUMBER, 
	"POPULATION" NUMBER, 
	"NOM_ZONE" VARCHAR2(100) NOT NULL ENABLE, 
	"LOCALISATION" VARCHAR2(255), 
	"SURFACE_ZONE" NUMBER(10,2), 
	"FREQUENCE" NUMBER, 
	"ID_UTILISATEUR" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_ZONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ZONE_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."UTILISATEUR" 
   (	"ID_UTILISATEUR" NUMBER, 
	"NOM" VARCHAR2(50) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	"NUM_TELEPHONE" VARCHAR2(20), 
	"MOT_DE_PASSE" VARCHAR2(255) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	"VILLE" VARCHAR2(50), 
	"CODE_POSTAL" VARCHAR2(10), 
	"SEXE" VARCHAR2(10), 
	"PHOTO" VARCHAR2(500), 
	 PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into TUNIWASTE.POUBELLE
SET DEFINE OFF;
Insert into TUNIWASTE.POUBELLE (ID_POUBELLE,LOCALISATION,NIVEAU,ETAT,TYPE,ID_ZONE,ID_CENTRE,ID_UTILISATEUR,ID_CAMION) values ('3','rue liberte ','50','Opérationnelle','Plastique','1',null,null,null);
REM INSERTING into TUNIWASTE.CAMION
SET DEFINE OFF;
REM INSERTING into TUNIWASTE.RECYCLAGE
SET DEFINE OFF;
REM INSERTING into TUNIWASTE.ZONE
SET DEFINE OFF;
Insert into TUNIWASTE.ZONE (ID_ZONE,POPULATION,NOM_ZONE,LOCALISATION,SURFACE_ZONE,FREQUENCE,ID_UTILISATEUR) values ('1','50000','Zone Nord','Tunis','120,5','3','1');
REM INSERTING into TUNIWASTE.UTILISATEUR
SET DEFINE OFF;
Insert into TUNIWASTE.UTILISATEUR (ID_UTILISATEUR,NOM,PRENOM,EMAIL,NUM_TELEPHONE,MOT_DE_PASSE,ROLE,VILLE,CODE_POSTAL,SEXE,PHOTO) values ('1','Ben Ali','Ahmed','ahmed@gmail.com','22334455','pass123','admin','Tunis','1000','M','photos/ahmed.png');
--------------------------------------------------------
--  DDL for Index SYS_C007417
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007417" ON "TUNIWASTE"."POUBELLE" ("ID_POUBELLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007413
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007413" ON "TUNIWASTE"."CAMION" ("ID_CAMION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007415
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007415" ON "TUNIWASTE"."RECYCLAGE" ("ID_CENTRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007410
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007410" ON "TUNIWASTE"."ZONE" ("ID_ZONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007406
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007406" ON "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007407
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007407" ON "TUNIWASTE"."UTILISATEUR" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table POUBELLE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD PRIMARY KEY ("ID_POUBELLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "TUNIWASTE"."POUBELLE" MODIFY ("ID_ZONE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table CAMION
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."CAMION" ADD PRIMARY KEY ("ID_CAMION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "TUNIWASTE"."CAMION" MODIFY ("ID_UTILISATEUR" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table RECYCLAGE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."RECYCLAGE" ADD PRIMARY KEY ("ID_CENTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table ZONE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."ZONE" ADD PRIMARY KEY ("ID_ZONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "TUNIWASTE"."ZONE" MODIFY ("ID_UTILISATEUR" NOT NULL ENABLE)
  ALTER TABLE "TUNIWASTE"."ZONE" MODIFY ("NOM_ZONE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."UTILISATEUR" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "TUNIWASTE"."UTILISATEUR" ADD PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "TUNIWASTE"."UTILISATEUR" MODIFY ("ROLE" NOT NULL ENABLE)
  ALTER TABLE "TUNIWASTE"."UTILISATEUR" MODIFY ("MOT_DE_PASSE" NOT NULL ENABLE)
  ALTER TABLE "TUNIWASTE"."UTILISATEUR" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "TUNIWASTE"."UTILISATEUR" MODIFY ("PRENOM" NOT NULL ENABLE)
  ALTER TABLE "TUNIWASTE"."UTILISATEUR" MODIFY ("NOM" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table POUBELLE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD CONSTRAINT "FK_POUBELLE_CAMION" FOREIGN KEY ("ID_CAMION")
	  REFERENCES "TUNIWASTE"."CAMION" ("ID_CAMION") ENABLE
  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD CONSTRAINT "FK_POUBELLE_CENTRE" FOREIGN KEY ("ID_CENTRE")
	  REFERENCES "TUNIWASTE"."RECYCLAGE" ("ID_CENTRE") ENABLE
  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD CONSTRAINT "FK_POUBELLE_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE
  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD CONSTRAINT "FK_POUBELLE_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "TUNIWASTE"."ZONE" ("ID_ZONE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CAMION
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."CAMION" ADD CONSTRAINT "FK_CAMION_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table RECYCLAGE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."RECYCLAGE" ADD CONSTRAINT "FK_RECYCLAGE_POUBELLE" FOREIGN KEY ("ID_POUBELLE")
	  REFERENCES "TUNIWASTE"."POUBELLE" ("ID_POUBELLE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ZONE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."ZONE" ADD CONSTRAINT "FK_ZONE_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE
