--------------------------------------------------------
--  Fichier créé - samedi-février-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_POUBELLE
--------------------------------------------------------

   CREATE SEQUENCE  "TUNIWASTE"."SEQ_POUBELLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Table CAMION
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."CAMION" 
   (	"ID_CAMION" NUMBER(*,0), 
	"TYPE_CAMION" VARCHAR2(50), 
	"CAPACITE" NUMBER(*,0), 
	"ETAT" VARCHAR2(30), 
	"NOM_CHAUFFEUR" VARCHAR2(50), 
	"NUM_CHAUFFEUR" VARCHAR2(20), 
	"LOCALISATION" VARCHAR2(100), 
	"TYPE_DECHET" VARCHAR2(50), 
	"NIVEAU_REMPLISSAGE" NUMBER(*,0), 
	"ID_UTILISATEUR" NUMBER(*,0), 
	"ID_ZONE" NUMBER(*,0), 
	 PRIMARY KEY ("ID_CAMION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_CAMION_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE, 
	 CONSTRAINT "FK_CAMION_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "TUNIWASTE"."ZONE" ("ID_ZONE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table POUBELLE
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."POUBELLE" 
   (	"ID_POUBELLE" NUMBER(*,0), 
	"LOCALISATION" VARCHAR2(100), 
	"NIVEAU" NUMBER(*,0), 
	"ETAT" VARCHAR2(30), 
	"TYPE" VARCHAR2(50), 
	"ID_CAMION" NUMBER(*,0), 
	"ID_ZONE" NUMBER(*,0), 
	 PRIMARY KEY ("ID_POUBELLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_POUBELLE_CAMION" FOREIGN KEY ("ID_CAMION")
	  REFERENCES "TUNIWASTE"."CAMION" ("ID_CAMION") ENABLE, 
	 CONSTRAINT "FK_POUBELLE_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "TUNIWASTE"."ZONE" ("ID_ZONE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table RECYCLAGE
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."RECYCLAGE" 
   (	"ID_CENTRE" NUMBER(*,0), 
	"RESPONSABLE" VARCHAR2(50), 
	"TYPE_DECHET" VARCHAR2(50), 
	"QUANTITE" FLOAT(126), 
	"DATE_RECYCLAGE" DATE, 
	"ID_POUBELLE" NUMBER(*,0), 
	 PRIMARY KEY ("ID_CENTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_RECYCLAGE_POUBELLE" FOREIGN KEY ("ID_POUBELLE")
	  REFERENCES "TUNIWASTE"."POUBELLE" ("ID_POUBELLE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."UTILISATEUR" 
   (	"ID_UTILISATEUR" NUMBER(*,0), 
	"NOM" VARCHAR2(50), 
	"PRENOM" VARCHAR2(50), 
	"EMAIL" VARCHAR2(100), 
	"NUM_TELEPHONE" VARCHAR2(20), 
	"MOT_PASSE" VARCHAR2(100), 
	"ROLE" VARCHAR2(30), 
	"VILLE" VARCHAR2(50), 
	"CODE_POSTALE" VARCHAR2(10), 
	"SEXE" VARCHAR2(10), 
	"PHOTO" VARCHAR2(255), 
	 PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ZONE
--------------------------------------------------------

  CREATE TABLE "TUNIWASTE"."ZONE" 
   (	"ID_ZONE" NUMBER(*,0), 
	"POPULATION" NUMBER(*,0), 
	"NOM_ZONE" VARCHAR2(50), 
	"LOCALISATION" VARCHAR2(100), 
	"SURFACE_ZONE" FLOAT(126), 
	"FREQUENCE" NUMBER(*,0), 
	 PRIMARY KEY ("ID_ZONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into TUNIWASTE.CAMION
SET DEFINE OFF;
REM INSERTING into TUNIWASTE.POUBELLE
SET DEFINE OFF;
REM INSERTING into TUNIWASTE.RECYCLAGE
SET DEFINE OFF;
REM INSERTING into TUNIWASTE.UTILISATEUR
SET DEFINE OFF;
REM INSERTING into TUNIWASTE.ZONE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007439
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007439" ON "TUNIWASTE"."CAMION" ("ID_CAMION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007442
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007442" ON "TUNIWASTE"."POUBELLE" ("ID_POUBELLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007445
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007445" ON "TUNIWASTE"."RECYCLAGE" ("ID_CENTRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007438
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007438" ON "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007437
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNIWASTE"."SYS_C007437" ON "TUNIWASTE"."ZONE" ("ID_ZONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table CAMION
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."CAMION" ADD PRIMARY KEY ("ID_CAMION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table POUBELLE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD PRIMARY KEY ("ID_POUBELLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table RECYCLAGE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."RECYCLAGE" ADD PRIMARY KEY ("ID_CENTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."UTILISATEUR" ADD PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table ZONE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."ZONE" ADD PRIMARY KEY ("ID_ZONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CAMION
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."CAMION" ADD CONSTRAINT "FK_CAMION_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "TUNIWASTE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE
  ALTER TABLE "TUNIWASTE"."CAMION" ADD CONSTRAINT "FK_CAMION_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "TUNIWASTE"."ZONE" ("ID_ZONE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table POUBELLE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD CONSTRAINT "FK_POUBELLE_CAMION" FOREIGN KEY ("ID_CAMION")
	  REFERENCES "TUNIWASTE"."CAMION" ("ID_CAMION") ENABLE
  ALTER TABLE "TUNIWASTE"."POUBELLE" ADD CONSTRAINT "FK_POUBELLE_ZONE" FOREIGN KEY ("ID_ZONE")
	  REFERENCES "TUNIWASTE"."ZONE" ("ID_ZONE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table RECYCLAGE
--------------------------------------------------------

  ALTER TABLE "TUNIWASTE"."RECYCLAGE" ADD CONSTRAINT "FK_RECYCLAGE_POUBELLE" FOREIGN KEY ("ID_POUBELLE")
	  REFERENCES "TUNIWASTE"."POUBELLE" ("ID_POUBELLE") ENABLE
